settings:

  check_interval: 500
  default_separator: ""

components:

  # - text: "all status "

  - Alsa:
      refresh_interval: 500
      signal: 6

      format:
        default: " ? {p}% "
        levels:
          - [100, "  {p}% "]
          - [40,  "  {p}% "]
          - [10,  "  {p}% "]
        muted: " MUTE({p}) "

  # - text: "|"

  - Backlight:
      refresh_interval: 500
      signal: 7

      path: "/sys/class/backlight/acpi_video0"

      format:
        default: "  {p} "

  # - text: "|"

  # - Battery:
  #     refresh_interval: 2000
  #     signal: 8

  #     format:
  #       full: " Full({p}) "
  #       charging: "  {p}% {t} "
  #       discharging:
  #         - [100, "  {p}% {t} "]
  #         - [70,  "  {p}% {t} "]
  #         - [50,  "  {p}% {t} "]
  #         - [30,  "  {p}% {t} "]
  #         - [10,  "  {p}% {t} "]
  #       not_charging: " ? {p}% {t} "
  #       default: " ? {p}% {t} "

  # - text: "|"

  # - Time:
  #     refresh_interval: 500
  #     signal: 9

  #     time: "%a %d %b %I:%M %P"

  #     format:
  #       default: " {t} "

