settings:

  check_interval: 100
  default_separator: "|"

components:

  - Backlight:
      refresh_interval: 500
      signal: 6

      path: "/sys/class/backlight/acpi_video0"

      format:
        default: "  {p} "
        levels:
          - [100, " A {p} "]
          - [50 , " B {p} "]
          - [25 , " C {p} "]

  - Battery:
      format:
        full: " Full({p}) "
        charging: "  {p}% {t} "
        discharging:
          - [100, "  {p}% {t} "]
          - [70,  "  {p}% {t} "]
          - [50,  "  {p}% {t} "]
          - [30,  "  {p}% {t} "]
          - [10,  "  {p}% {t} "]
        not_charging: " ? {p}% {t} "
        default: " ? {p}% {t} "

  - Time:
      refresh_interval: 500
      signal: 8

      time: "%a %d %b %I:%M %P"

      format:
        default: " {t} "

  - Alsa:

