settings:

  check_interval: 500
  default_separator: ""

components:

  - Command:
      refresh_interval: 1000
      shell_command: "echo -n 'all status '"

  - Alsa:
      refresh_interval: 1000
      format:
        default: " ? {p}% "
        muted: " MUTE({p}) "
        levels:
          - [100, "  {p}% "]
          - [40,  "  {p}% "]
          - [10,  "  {p}% "]

  - text: "|"

  - Backlight:
      refresh_interval: 500
      path: "/sys/class/backlight/acpi_video0"
      format:
        default: "  {p} "

  - text: "|"

  - Battery:
      refresh_interval: 2000
      format:
        default: " ? {p}% {t} "
        full: " Full({p}) "
        charging: "  {p}% {t} "
        not_charging: " ? {p}% "
        discharging:
          - [100, "  {p}% {t} "]
          - [70,  "  {p}% {t} "]
          - [50,  "  {p}% {t} "]
          - [30,  "  {p}% {t} "]
          - [10,  "  {p}% {t} "]

  - text: "|"

  - Time:
      refresh_interval: 1000
      time: "%a %d %b %I:%M %P"
      format:
        default: " {t} "

