settings:

  check_interval: 100
  default_separator: "|"

components:

  - Alsa:
      refresh_interval: 500
      signal: 5

      volume_fmt:
        left_pad: " v: "
        right_pad: "% "

      # muted_fmt: " {} "  # plug this directly into the Display::fmt() function?
      muted_fmt:
        left_pad: " "
        right_pad: " "

  - Backlight:
      refresh_interval: 500
      signal: 6

      left_pad: " b: "
      right_pad: " "

  - Battery:
      refresh_interval: 1000
      signal: 7

      path: "/sys/class/power_supply/BAT0"

      format:
        vars:
          def: "{percent}% {time_remaining}"
        full: " Full({percent}) "
        charging: "  {$def} "
        not_charging: " ? {$def} "
        discharging:
          - [100, "  {$def} "]
          - [70,  "  {$def} "]
          - [50,  "  {$def} "]
          - [30,  "  {$def} "]
          - [10,  "  {$def} "]

  - Time:
      refresh_interval: 500
      signal: 8

      format: "%a %d %b %I:%M %P"
